version: "3"
services:
  app:
    container_name: {{ cookiecutter.project_slug }}
    build:
      context: .
      args:
        NODE_VERSION: "{{ cookiecutter.node_version }}"
    ports:
      - "{{ cookiecutter.docker_port }}:3000"
